name: Publish PyVMCON to The Python Package Index (PyPI)

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    name: Build and publish Python distributions PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: "3.x"
      - name: Install pypa/build
        run: python3 -m pip install build
      - name: Build a binary wheel and a source tarball
        run: python3 -m build --sdist --wheel --outdir dist/ .
      - name: Publish PyVMCON to PyPI
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e
