name: PyVMCON quality assurance workflow
permissions:
  contents: read
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  quality_assure_pyvmcon:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: "3.10"
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files
